name: Docs PR Spellcheck
on:
  pull_request:
    branches:
      - 'dev'
    files:
      - '**Doxyfile'
      - '**docpages/**'
      - '**/*.h'
      - '**/documentation-check.yml'
  push:
    files:
      - '**/documentation-check.yml'

permissions:
  contents: read # This only needs to read the contents of a PR.

jobs:
  docs:
    name: Check Documentation Spelling
    runs-on: ubuntu-20.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout D++
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Check docs spelling
        run: npx -y cspell lint --language-id=cpp --no-progress --no-summary --show-context --show-suggestions --relative --color docpages/*.md include/dpp/*.h
