name: Docs PR Spellcheck
on:
  pull_request:
    branches:
      - 'dev'
    files:
      - '**Doxyfile'
      - '**docpages/**'
      - '**/*.h'
      - '**/documentation-check.yml'
  push:
    files:
      - '**/documentation-check.yml'

permissions:
  contents: read # This only needs to read the contents of a PR.

jobs:
  docs:
    name: Check Documentation Spelling
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout D++
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check docs spelling
        run: git diff origin/dev --name-only --diff-filter=ACMRTUXB | npx -y cspell lint --language-id=cpp --no-progress --no-summary --show-context --show-suggestions --relative --color --file-list stdin --no-must-find-file

