name: Docs PR Spellcheck
on:
  pull_request:
    branches:
      - 'dev'
    files:
      - '**Doxyfile'
      - '**docpages/**'
      - '**/*.h'
      - '**/documentation-check.yml'
  push:
    files:
      - '**/documentation-check.yml'

permissions:
  contents: read # This only needs to read the contents of a PR.

jobs:
  docs:
    name: Check Documentation Spelling
    runs-on: ubuntu-20.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout D++
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Check docs spelling
        run: npx -y cspell lint --language-id=cpp --no-progress --no-summary --show-context --show-suggestions --relative --color docpages/*.md include/dpp/*.h
