name: Docs PR Spellcheck
on:
  pull_request:
    branches:
      - 'dev'
    files:
      - '**Doxyfile'
      - '**docpages/**'
      - '**/*.h'
      - '**/documentation-check.yml'
  push:
    files:
      - '**/documentation-check.yml'

permissions:
  contents: read # This only needs to read the contents of a PR.

jobs:
  docs:
    name: Check Documentation Spelling
    runs-on: ubuntu-20.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout D++
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check docs spelling
        run: npx -y cspell lint --language-id=cpp --no-progress --no-summary --show-context --show-suggestions --relative --color docpages/*.md include/dpp/*.h
