name: misspell-fixer
on:
  schedule:
    - cron: '0 0 15 * *'
jobs:
  build:
    if: github.repository == 'brainboxdotcc/DPP'
    runs-on: ubuntu-latest
    env:
      REF_BRANCH: ${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name : Set a couple env variables
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "REF_BRANCH=${REF_BRANCH//refs\/heads\//}" >> $GITHUB_ENV
    - name: Whitelist some directories and files
      run: |
        echo "^./.github/workflows" > ${{ runner.workspace }}/DPP/.misspell-fixer.ignore
    - uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rvnfuRVD .'
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.REF_BRANCH }}+fix-spellings-${{ env.DATE }}
        author: 'D++ Repobot <noreply@brainbox.cc>'
        committer: 'D++ Repobot <noreply@brainbox.cc>'
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
        reviewers: 'braindigitalis'
